# -*- coding: utf-8 -*-
"""แบบที่ 12 Lag 7 วันNo ShuffleBackwardCalendar day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QW38FPlwcA21yv6HT97AX_W4xd6RABHt
"""

!pip install pandas_market_calendars
!pip install yfinance scikit-learn

# นำเข้าไลบรารีที่จำเป็น
import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pandas_market_calendars as mcal

# ไลบรารีสำหรับ Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# ------------------------------
# 1. ดาวน์โหลดข้อมูลหุ้น
# ------------------------------
tickers = ["TSM"]

# กำหนดช่วงวันที่
start_date = datetime(2017, 1, 1)
end_date   = datetime(2018, 12, 31)
#end_date = datetime.today()
#start_date = end_date - timedelta(days=1*365)  # 5 ปี

all_data_list = []

for ticker in tickers:
    print(f"📥 Downloading {ticker} ...")
    data = yf.download(ticker, start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))

    if data.empty:
        print(f"❌ No data for {ticker}")
        continue

    data.reset_index(inplace=True)

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in data.columns.values]

    def clean_columns(cols):
        cleaned = []
        for col in cols:
            if 'Date' in col:
                cleaned.append('Date')
            else:
                cleaned.append(col.split()[0])
        return cleaned

    data.columns = clean_columns(data.columns)
    data['Symbol'] = ticker.upper()

    wanted_cols = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume', 'Symbol']
    data = data[[col for col in wanted_cols if col in data.columns]]

    all_data_list.append(data)

flat_df = pd.concat(all_data_list, ignore_index=True)
flat_df['Date'] = pd.to_datetime(flat_df['Date']).dt.normalize()
flat_df['Symbol'] = flat_df['Symbol'].astype(str).str.upper()
flat_df = flat_df.sort_values(by=['Symbol', 'Date']).reset_index(drop=True)

import pandas as pd
import pandas_market_calendars as mcal

# 1. สร้าง continuous date range
all_dates = pd.DataFrame({'Date': pd.date_range(flat_df['Date'].min(), flat_df['Date'].max())})

# 2. ขยาย Symbol list ให้ครบทุกวัน
symbols = flat_df['Symbol'].unique()
expanded_list = []
for sym in symbols:
    temp = all_dates.copy()
    temp['Symbol'] = sym
    expanded_list.append(temp)
all_dates_symbols = pd.concat(expanded_list, ignore_index=True)

# 3. merge กับ flat_df ของราคาหุ้น
full_df = all_dates_symbols.merge(flat_df, on=['Date','Symbol'], how='left')

# 4. สร้าง holiday / weekend
nyse = mcal.get_calendar('NYSE')
schedule = nyse.schedule(start_date=full_df['Date'].min(), end_date=full_df['Date'].max())
business_days = schedule.index.normalize()
business_set = set(business_days)

full_df['holiday'] = (~full_df['Date'].isin(business_set)).astype(int)
full_df['weekend'] = full_df['Date'].dt.dayofweek.isin([5,6]).astype(int)

# 5. pre_holiday / post_holiday
def compute_pre_holiday(date):
    return int((date + pd.Timedelta(days=1)) not in business_set)

def compute_post_holiday(date):
    return int((date - pd.Timedelta(days=1)) not in business_set)

full_df['pre_holiday'] = full_df['Date'].apply(compute_pre_holiday)
full_df['post_holiday'] = full_df['Date'].apply(compute_post_holiday)

# 6. ตรวจสอบ
print(full_df[['Date','Symbol','Close']].head(30))

# ----------------------------
# 1) เติมค่าว่าง Close, Open ด้วย Backward Fill
# ----------------------------
price_cols = ['Close', 'Open']
for col in price_cols:
    full_df[col] = full_df.groupby('Symbol')[col].transform(lambda x: x.bfill())

# ----------------------------
# 2) สร้าง lag 7 วันสำหรับ Close
# ----------------------------
lag_cols = []
for lag in range(1, 8):  # 1 ถึง 7 วัน
    col_name = f'Close_lag{lag}'
    full_df[col_name] = full_df.groupby('Symbol')['Close'].shift(lag)
    lag_cols.append(col_name)

# ----------------------------
# 3) เติมค่า NaN ของ lag columns ด้วย Backward Fill
# ----------------------------
for col in price_cols:
    full_df[col] = full_df.groupby('Symbol')[col].transform(lambda x: x.bfill())

# ----------------------------
# 4) ตรวจสอบผลลัพธ์
# ----------------------------
print("จำนวน NaN ที่เหลือในแต่ละคอลัมน์:")
print(full_df[['Close','Open'] + lag_cols].isna().sum())

# แสดงตัวอย่าง
cols_to_show = ['Date','Symbol','Close'] + lag_cols
print(full_df[cols_to_show].head(15))

# 9. สร้าง Target: Close ของวันถัดไป
full_df['Close_next'] = full_df.groupby('Symbol')['Close'].shift(-1)

# 10. สร้าง Feature Matrix X
lag_cols = [f'Close_lag{i}' for i in range(1,8)]  # Close_lag1 ... Close_lag7

X_cols = lag_cols
X = full_df[X_cols]
# Target
y = full_df['Close_next']

# ตรวจสอบตัวอย่าง
print("Feature Matrix X:")
print(X.head(10))
print("\nTarget y:")
print(y.head(10))

# 11. ลบ row ที่มี NaN ใน X หรือ y
data_ml = pd.concat([X, y], axis=1)  # รวม X และ y ชั่วคราว
data_ml_clean = data_ml.dropna().reset_index(drop=True)

# แยกกลับเป็น X และ y
X_clean = data_ml_clean[X_cols]
y_clean = data_ml_clean['Close_next']

# ตรวจสอบตัวอย่าง
print("Feature Matrix X (clean):")
print(X_clean.head(10))
print("\nTarget y (clean):")
print(y_clean.head(10))

from sklearn.preprocessing import StandardScaler

# 1. สร้าง scaler
scaler = StandardScaler()

# 2. fit & transform X_clean
X_scaled = scaler.fit_transform(X_clean)

# 3. ตรวจสอบตัวอย่าง
import pandas as pd
X_scaled_df = pd.DataFrame(X_scaled, columns=X_cols)
print(X_scaled_df.head(10))

from sklearn.model_selection import train_test_split

# 12. แบ่ง dataset
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_clean, test_size=0.2, random_state=42, shuffle=False
)

# ตรวจสอบขนาด dataset
print(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
print(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")

import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))

# plot y_train
plt.plot(y_train.index, y_train.values, color='green', label='y_train (Target)', linewidth=1.5)

# plot y_test
plt.plot(y_test.index, y_test.values, color='orange', label='y_test (Target)', linewidth=1.5)

plt.title('Target: Close Price of Next Day (Train & Test)')
plt.xlabel('Index')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np
import pandas as pd

# สร้าง dictionary สำหรับโมเดล
models = {
    'LinearRegression': LinearRegression(),
    'Ridge': Ridge(alpha=1.0),
    'Lasso': Lasso(alpha=0.1),
    'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, random_state=42),
    'DecisionTree': DecisionTreeRegressor(random_state=42),
    'KNN': KNeighborsRegressor(n_neighbors=5),
    'SVR': SVR(kernel='rbf', C=1.0, epsilon=0.1),
    'XGBoost': XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42, objective='reg:squarederror')
}

# เก็บผลลัพธ์
results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)

    results.append({'Model': name, 'RMSE': rmse, 'R2': r2, 'MAE': mae})
    print(f"{name} -> RMSE: {rmse:.4f}, R2: {r2:.4f}, MAE: {mae:.4f}")

# แปลงเป็น DataFrame และเรียงลำดับความแม่นยำ (R² มาก → น้อย)
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by="R2", ascending=False).reset_index(drop=True)

print("\n📊 แบบที่_5_Baseline_TSM_Trading_day_สร้าง_365_เติมค่าว่าง_Backward_Fill_Lag_7_Day_drop ผลลัพธ์เรียงตามความแม่นยำ (R²):")
print(results_df)

results_df.to_csv('แบบที่ 12 Lag 7 วันNo ShuffleBackwardCalendar day.csv', index=False)

import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))

# plot ราคาจริง y_test
plt.plot(y_test.index, y_test.values, color='black', label='Actual Close_next', linewidth=2)

# ใช้ colormap เพื่อเลือกสีให้ครบทุกโมเดล
colors = plt.cm.tab10.colors  # tab10 มี 10 สี
for i, (name, model) in enumerate(models.items()):
    y_pred = model.predict(X_test)
    plt.plot(y_test.index, y_pred, color=colors[i % len(colors)], label=name, linewidth=1.5)

plt.title('Prediction vs Actual Close Price (Next Day)')
plt.xlabel('Index')
plt.ylabel('Price')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

"""***เรียงโมเดลจาก R² สูงสุด → ต่ำสุด ก่อนสร้าง subplot***"""

import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import numpy as np
import pandas as pd

# สร้าง DataFrame เก็บผลลัพธ์ของแต่ละโมเดล
results_list = []

for name, model in models.items():
    y_pred = model.predict(X_test)
    rmse = np.sqrt(mean_squared_error(y_test, y_pred))
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    results_list.append({'Model': name, 'ModelObj': model, 'R2': r2, 'RMSE': rmse, 'MAE': mae})

results_df = pd.DataFrame(results_list)
# เรียงลำดับจาก R² สูงสุด → ต่ำสุด
results_df = results_df.sort_values(by='R2', ascending=False).reset_index(drop=True)

# ---------------------------
# สร้าง subplot
# ---------------------------
n_models = len(results_df)
n_cols = 3
n_rows = (n_models + n_cols - 1) // n_cols

plt.figure(figsize=(16, 4*n_rows))
plt.suptitle("Scenario 6: Baseline TSM - Calendar Days 365 -Backward Fill Close Price - 7-Day Lag - Drop NAN",
             fontsize=16, y=1.02)
for i, row in results_df.iterrows():
    name = row['Model']
    model = row['ModelObj']
    y_pred = model.predict(X_test)

    plt.subplot(n_rows, n_cols, i+1)
    plt.plot(y_test.index, y_test.values, color='black', label='Actual', linewidth=2)
    plt.plot(y_test.index, y_pred, color='red', label='Predicted', linewidth=1.5)

    plt.title(f"{name}\nR²={row['R2']:.4f}, RMSE={row['RMSE']:.4f}, MAE={row['MAE']:.4f}")
    plt.xlabel("Index")
    plt.ylabel("Price")
    plt.legend()
    plt.grid(True)

plt.tight_layout()
plt.show()